<?php
declare(strict_types=1);
final class NewsService {
 public static function fetchAll():array{$sources=db()->query("SELECT s.*,c.name category_name FROM sources s LEFT JOIN categories c ON c.id=s.category_id WHERE s.active=true AND s.rss_url IS NOT NULL ORDER BY s.name")->fetchAll();$imported=0;$errors=[];foreach($sources as $s){try{$imported+=self::fetchRss($s);}catch(Throwable $e){$errors[]=$s['name'];error_log($s['name'].': '.$e->getMessage());}}try{$imported+=self::fetchGdelt();}catch(Throwable $e){$errors[]='GDELT';error_log('GDELT: '.$e->getMessage());}return ['imported'=>$imported,'sources'=>count($sources),'errors'=>$errors];}
 private static function http(string $url):string{if(!valid_url($url))throw new RuntimeException('Invalid source URL.');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>20,CURLOPT_MAXFILESIZE=>2000000,CURLOPT_USERAGENT=>'SignalDeskBot/1.0 (+news aggregation; contact admin)']);$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($body===false||$status>=400)throw new RuntimeException('HTTP fetch failed.');return $body;}
 private static function fetchRss(array $s):int{$xml=@simplexml_load_string(self::http($s['rss_url']));if(!$xml||!isset($xml->channel->item))return 0;$pdo=db();$st=$pdo->prepare("INSERT INTO news_items(source_id,external_guid,title,description,url,image_url,published_at,content_hash) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING");$count=0;foreach($xml->channel->item as $i){$url=valid_url((string)$i->link);$title=clean_string((string)$i->title,500);if(!$url||$title==='')continue;$desc=clean_string(strip_tags((string)$i->description),4000);$raw=(array)$i->children('media',true);$img=valid_url((string)($raw['content']['url']??''));if(!$img)$img=valid_url((string)$i->enclosure['url']??'');$ts=strtotime((string)$i->pubDate);$date=$ts?date('c',$ts):null;$guid=clean_string((string)($i->guid?:$url),1000);$hash=hash('sha256',self::normalizeUrl($url));$st->execute([$s['id'],$guid,$title,$desc,$url,$img,$date,$hash]);$count+=(int)$st->rowCount();}return $count;}
 private static function fetchGdelt():int{$data=json_decode(self::http('https://api.gdeltproject.org/api/v2/doc/doc?query=language:english&mode=artlist&maxrecords=50&format=json&sort=datedesc'),true);if(!is_array($data))throw new RuntimeException('Invalid GDELT response.');$pdo=db();$sid=$pdo->query("SELECT id FROM sources WHERE name='GDELT' LIMIT 1")->fetchColumn();if(!$sid){$x=$pdo->prepare("INSERT INTO sources(name,website_url,active) VALUES('GDELT','https://www.gdeltproject.org',true) RETURNING id");$x->execute();$sid=$x->fetchColumn();}$st=$pdo->prepare("INSERT INTO news_items(source_id,external_guid,title,description,url,image_url,published_at,content_hash) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING");$count=0;foreach(($data['articles']??[]) as $a){$url=valid_url($a['url']??'');if(!$url)continue;$ts=strtotime((string)($a['seendate']??''));$st->execute([$sid,$url,clean_string($a['title']??'Untitled',500), '',$url,valid_url($a['socialimage']??''),$ts?date('c',$ts):null,hash('sha256',self::normalizeUrl($url))]);$count+=(int)$st->rowCount();}return $count;}
 private static function normalizeUrl(string $url):string{$p=parse_url($url);return strtolower(($p['scheme']??'').'://'.($p['host']??'').($p['path']??''));}
 public static function health():array{$r=['RSS'=>'NOT CHECKED','GDELT'=>'NOT CHECKED'];$feed=db()->query("SELECT rss_url FROM sources WHERE active=true AND rss_url IS NOT NULL LIMIT 1")->fetchColumn();if($feed){try{self::http($feed);$r['RSS']='WORKING';}catch(Throwable){$r['RSS']='FAILING';}}try{self::http('https://api.gdeltproject.org/api/v2/doc/doc?query=test&mode=artlist&maxrecords=1&format=json');$r['GDELT']='WORKING';}catch(Throwable){$r['GDELT']='FAILING';}return $r;}
}
?>
