<?php
require __DIR__.'/../app/config/bootstrap.php';require __DIR__.'/../app/services/NewsService.php';require __DIR__.'/../app/services/AIService.php';
$path=rtrim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH)?:'/','/')?:'/';$method=$_SERVER['REQUEST_METHOD'];
if($path==='/'||$path==='/login'){redirect('/admin');}
function q(string $sql,array $args=[]):array{$s=db()->prepare($sql);$s->execute($args);return $s->fetchAll();}function one(string $sql,array $args=[]):?array{$r=q($sql,$args);return $r[0]??null;}function articleInput(array $d):array{$title=clean_string($d['title']??'',220);$content=clean_string($d['content']??'',50000);if($title===''||$content==='')throw new InvalidArgumentException('Headline and article body are required.');return ['title'=>$title,'slug'=>slugify(clean_string($d['slug']??$title,220)),'summary'=>clean_string($d['summary']??'',2000),'content'=>$content,'seo_title'=>clean_string($d['seo_title']??$title,220),'meta_description'=>clean_string($d['meta_description']??'',320),'featured_image'=>valid_url($d['featured_image']??''),'category_id'=>!empty($d['category_id'])?(int)$d['category_id']:null,'source_url'=>valid_url($d['source_url']??''),'source_name'=>clean_string($d['source_name']??'',160),'ai_generated'=>($d['ai_generated']??'0')==='1'];}
if($path==='/login'){if($method==='POST'){verify_csrf();rate_limit('login:'.($_SERVER['REMOTE_ADDR']??'unknown'),8,300);$u=one('SELECT * FROM users WHERE lower(email)=lower(?)',[trim($_POST['email']??'')]);if($u&&password_verify($_POST['password']??'',$u['password_hash'])&&$u['role']==='admin'){session_regenerate_id(true);$_SESSION['admin_id']=$u['id'];$_SESSION['admin_name']=$u['name'];$_SESSION['admin_role']=$u['role'];redirect('/admin');}flash('Invalid credentials','error');}render('login',['title'=>'Sign in']);exit;}
if($path==='/logout'){if($method==='POST'){verify_csrf();session_destroy();redirect('/');}redirect('/');}
if(str_starts_with($path,'/cron/')){$token=$_GET['token']??($_SERVER['HTTP_X_CRON_SECRET']??'');if(!$token||!hash_equals((string)config('cron_secret'),(string)$token))json_response(['error'=>'Unauthorized'],401);if($path==='/cron/fetch-news.php')json_response(NewsService::fetchAll());if($path==='/cron/generate-articles.php')json_response(['status'=>'review_required','generated'=>0,'message'=>'Automatic publishing is intentionally disabled; use the review workflow.']);json_response(['error'=>'Not found'],404);}
if($path==='/api/fetch-news'&&$method==='POST'){require_admin();verify_csrf();rate_limit('fetch-news',3,60);json_response(NewsService::fetchAll());}
if($path==='/api/generate'&&$method==='POST'){require_admin();verify_csrf();rate_limit('generate',10,300);$item=one('SELECT n.*,s.name source_name FROM news_items n JOIN sources s ON s.id=n.source_id WHERE n.id=?',[(int)($_POST['news_id']??0)]);if(!$item)json_response(['error'=>'News item not found'],404);$r=AIService::generate($item,(string)($_POST['provider']??''),clean_string($_POST['model']??'',120),clean_string($_POST['style']??'Professional News',60),clean_string($_POST['length']??'Medium',20),clean_string($_POST['instructions']??'',2000));$r['source']=['url'=>$item['url'],'name'=>$item['source_name'],'news_id'=>$item['id']];json_response($r);}
if(str_starts_with($path,'/admin')){require_admin();
 if($path==='/admin'){ $stats=['news'=>one('SELECT count(*) n FROM news_items')['n'],'drafts'=>one("SELECT count(*) n FROM articles WHERE status='draft'")['n'],'published'=>one("SELECT count(*) n FROM articles WHERE status='published'")['n'],'sources'=>one('SELECT count(*) n FROM sources WHERE active=true')['n'],'generations'=>one('SELECT count(*) n FROM ai_generations')['n']];render('dashboard',['title'=>'Dashboard','stats'=>$stats,'recent'=>q('SELECT n.*,s.name source_name FROM news_items n JOIN sources s ON s.id=n.source_id ORDER BY n.discovered_at DESC LIMIT 8')],true);exit;}
 if($path==='/admin/news-discovery'){ $where=[];$args=[];if(!empty($_GET['q'])){$where[]='(n.title ILIKE ? OR n.description ILIKE ?)';$args[]='%'.clean_string($_GET['q'],100).'%';$args[]=$args[0];}if(!empty($_GET['source'])){$where[]='n.source_id=?';$args[]=(int)$_GET['source'];}if(!empty($_GET['category'])){$where[]='s.category_id=?';$args[]=(int)$_GET['category'];}$sql='SELECT n.*,s.name source_name,c.name category_name FROM news_items n JOIN sources s ON s.id=n.source_id LEFT JOIN categories c ON c.id=s.category_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY n.published_at DESC NULLS LAST LIMIT 200';render('news-discovery',['title'=>'News Discovery','items'=>q($sql,$args),'sources'=>q('SELECT id,name FROM sources ORDER BY name'),'categories'=>q('SELECT id,name FROM categories ORDER BY name')],true);exit;}
 if($path==='/admin/ai-studio'&&$method==='GET'){render('ai-studio',['title'=>'AI Studio','items'=>q('SELECT n.*,s.name source_name FROM news_items n JOIN sources s ON s.id=n.source_id ORDER BY n.published_at DESC NULLS LAST LIMIT 100'),'providers'=>AIService::available(),'categories'=>q('SELECT id,name FROM categories ORDER BY name')],true);exit;}
 if($path==='/admin/articles'){ $status=($_GET['status']??'draft')==='published'?'published':'draft';render('articles',['title'=>ucfirst($status).' Articles','status'=>$status,'articles'=>q('SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.status=? ORDER BY a.updated_at DESC',[$status])],true);exit;}
 if(preg_match('#^/admin/articles/(\d+)/edit$#',$path,$m)){ $a=one('SELECT * FROM articles WHERE id=?',[(int)$m[1]]);if(!$a){http_response_code(404);exit('Article not found');}render('article-editor',['title'=>'Edit Article','article'=>$a,'categories'=>q('SELECT id,name FROM categories ORDER BY name')],true);exit;}
 if($path==='/admin/articles/save'&&$method==='POST'){verify_csrf();$d=articleInput($_POST);$status=($_POST['status']??'draft')==='published'?'published':'draft';$pdo=db();$pdo->beginTransaction();$id=!empty($_POST['id'])?(int)$_POST['id']:0;if($id){$s=$pdo->prepare('UPDATE articles SET title=?,slug=?,summary=?,content=?,seo_title=?,meta_description=?,featured_image=?,category_id=?,source_url=?,source_name=?,ai_generated=?,status=?,published_at=CASE WHEN ?=\'published\' THEN COALESCE(published_at,NOW()) ELSE published_at END,updated_at=NOW() WHERE id=?');$s->execute([$d['title'],$d['slug'],$d['summary'],$d['content'],$d['seo_title'],$d['meta_description'],$d['featured_image'],$d['category_id'],$d['source_url'],$d['source_name'],$d['ai_generated'],$status,$status,$id]);}else{$s=$pdo->prepare('INSERT INTO articles(title,slug,summary,content,seo_title,meta_description,featured_image,category_id,status,source_url,source_name,ai_generated,published_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CASE WHEN ?=\'published\' THEN NOW() ELSE NULL END) RETURNING id');$s->execute([$d['title'],$d['slug'],$d['summary'],$d['content'],$d['seo_title'],$d['meta_description'],$d['featured_image'],$d['category_id'],$status,$d['source_url'],$d['source_name'],$d['ai_generated'],$status]);$id=(int)$s->fetchColumn();}if(!empty($_POST['news_id']))$pdo->prepare('INSERT INTO article_sources(article_id,news_item_id) VALUES(?,?) ON CONFLICT DO NOTHING')->execute([$id,(int)$_POST['news_id']]);if(!empty($_POST['generation_prompt'])){$g=$pdo->prepare('INSERT INTO ai_generations(article_id,provider,model,prompt,response) VALUES(?,?,?,?,?)');$g->execute([$id,clean_string($_POST['generation_provider']??'',40),clean_string($_POST['generation_model']??'',120),clean_string($_POST['generation_prompt']??'',30000),clean_string($_POST['generation_response']??'',50000)]);}$tagNames=array_slice(array_filter(array_map(fn($x)=>clean_string($x,80),preg_split('/[,\n]+/',(string)($_POST['tags']??'')))),0,20);$pdo->prepare('DELETE FROM article_tags WHERE article_id=?')->execute([$id]);foreach($tagNames as $tag){$slug=slugify($tag);$pdo->prepare('INSERT INTO tags(name,slug) VALUES(?,?) ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name')->execute([$tag,$slug]);$tid=$pdo->prepare('SELECT id FROM tags WHERE slug=?');$tid->execute([$slug]);$pdo->prepare('INSERT INTO article_tags(article_id,tag_id) VALUES(?,?) ON CONFLICT DO NOTHING')->execute([$id,$tid->fetchColumn()]);}$pdo->commit();flash($status==='published'?'Article published':'Draft saved');redirect('/admin/articles?status='.$status);}
 if($path==='/admin/categories'&&$method==='GET'){render('categories',['title'=>'Categories','categories'=>q('SELECT c.*,count(a.id) article_count FROM categories c LEFT JOIN articles a ON a.category_id=c.id GROUP BY c.id ORDER BY c.name')],true);exit;}
 if($path==='/admin/categories/save'&&$method==='POST'){verify_csrf();$n=clean_string($_POST['name']??'',80);if($n==='')throw new InvalidArgumentException('Category name is required.');$s=db()->prepare('INSERT INTO categories(name,slug,description) VALUES(?,?,?) ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description');$s->execute([$n,slugify($n),clean_string($_POST['description']??'',500)]);flash('Category saved');redirect('/admin/categories');}
 if($path==='/admin/sources'&&$method==='GET'){render('sources',['title'=>'Sources','sources'=>q('SELECT s.*,c.name category_name FROM sources s LEFT JOIN categories c ON c.id=s.category_id ORDER BY s.name'),'categories'=>q('SELECT id,name FROM categories ORDER BY name')],true);exit;}
 if($path==='/admin/sources/save'&&$method==='POST'){verify_csrf();$name=clean_string($_POST['name']??'',120);$rss=valid_url($_POST['rss_url']??'');if($name===''||!$rss)throw new InvalidArgumentException('Source name and valid RSS URL are required.');$s=db()->prepare('INSERT INTO sources(name,website_url,rss_url,category_id,active) VALUES(?,?,?,?,?)');$s->execute([$name,valid_url($_POST['website_url']??''),$rss,!empty($_POST['category_id'])?(int)$_POST['category_id']:null,!empty($_POST['active'])]);flash('Source added');redirect('/admin/sources');}
 if($path==='/admin/sources/toggle'&&$method==='POST'){verify_csrf();$s=db()->prepare('UPDATE sources SET active=NOT active,updated_at=NOW() WHERE id=?');$s->execute([(int)($_POST['id']??0)]);flash('Source status updated');redirect('/admin/sources');}
 if($path==='/admin/health'){try{$checks=['Database'=>'CONNECTED']+NewsService::health();}catch(Throwable){$checks=['Database'=>'FAILING','RSS'=>'NOT CHECKED','GDELT'=>'NOT CHECKED'];}$checks+=['Groq'=>env('GROQ_API_KEY')?'CONFIGURED':'NOT CONFIGURED','Gemini'=>env('GEMINI_API_KEY')?'CONFIGURED':'NOT CONFIGURED','OpenRouter'=>env('OPENROUTER_API_KEY')?'CONFIGURED':'NOT CONFIGURED'];render('health',['title'=>'System Health','checks'=>$checks],true);exit;}
 render('dashboard',['title'=>'Dashboard','stats'=>[],'recent'=>[]],true);exit;}
if($path==='/news'){render('home',['title'=>'Latest News','articles'=>q("SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.status='published' ORDER BY a.published_at DESC LIMIT 50"),'featured'=>one("SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.status='published' ORDER BY a.published_at DESC LIMIT 1")]);exit;}
if($path==='/search'){ $term=clean_string($_GET['q']??'',100);render('home',['title'=>'Search','articles'=>$term?q("SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.status='published' AND (a.title ILIKE ? OR a.summary ILIKE ? OR a.content ILIKE ?) ORDER BY a.published_at DESC LIMIT 50",['%'.$term.'%','%'.$term.'%','%'.$term.'%']):[],'featured'=>null,'search'=>$term]);exit;}
if(preg_match('#^/category/([^/]+)$#',$path,$m)){render('home',['title'=>'Category','articles'=>q("SELECT a.*,c.name category_name FROM articles a JOIN categories c ON c.id=a.category_id WHERE a.status='published' AND c.slug=? ORDER BY a.published_at DESC LIMIT 50",[$m[1]]),'featured'=>null]);exit;}
if(preg_match('#^/news/([^/]+)$#',$path,$m)){ $a=one("SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.slug=? AND a.status='published'",[$m[1]]);if(!$a){http_response_code(404);exit('Article not found');}render('article',['title'=>$a['title'],'article'=>$a,'related'=>q("SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.status='published' AND a.id<>? AND (a.category_id=? OR a.category_id IS NULL) ORDER BY a.published_at DESC LIMIT 3",[$a['id'],$a['category_id']])]);exit;}
render('home',['title'=>'SignalDesk','articles'=>q("SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.status='published' ORDER BY a.published_at DESC LIMIT 12"),'featured'=>one("SELECT a.*,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id WHERE a.status='published' ORDER BY a.published_at DESC LIMIT 1")]);
?>
